// <auto-generated />
using System;
using System.Collections.Generic;
using HabitTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HabitTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260424182756_AddOutboxMessages")]
    partial class AddOutboxMessages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "condition_key", new[] { "total_metric_volume", "positive_streak", "negative_streak", "perfect_day_streak", "any_x_habits_streak", "first_action", "synergy_combo", "category_total_executions", "time_slot_streak", "consistent_bedtime_streak", "sleep_debt_cleared", "affect_stability", "affect_high_dominance" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "frequency_type", new[] { "daily", "weekly", "monthly", "once" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "proposal_status", new[] { "pending", "implemented", "rejected" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HabitTracker.Domain.Entities.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color_hex");

                    b.Property<int>("ConditionKey")
                        .HasColumnType("integer")
                        .HasColumnName("condition_key");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("HabitId")
                        .HasColumnType("integer")
                        .HasColumnName("habit_id");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("icon_url");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<int?>("TargetValue")
                        .HasColumnType("integer")
                        .HasColumnName("target_value");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_achievements");

                    b.HasIndex("HabitId")
                        .HasDatabaseName("ix_achievements_habit_id");

                    b.ToTable("achievements");
                });

            modelBuilder.Entity("HabitTracker.Domain.Entities.AffectEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ArousalScore")
                        .HasColumnType("integer")
                        .HasColumnName("arousal_score");

                    b.PrimitiveCollection<List<string>>("ContextTags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("context_tags")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<int>("DominanceScore")
                        .HasColumnType("integer")
                        .HasColumnName("dominance_score");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int>("PleasureScore")
                        .HasColumnType("integer")
                        .HasColumnName("pleasure_score");

                    b.Property<DateTime>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_affect_entries");

                    b.HasIndex("ContextTags")
                        .HasDatabaseName("idx_affect_tags");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ContextTags"), "gin");

                    b.HasIndex("UserId", "RecordedAt")
                        .HasDatabaseName("idx_affect_user_time");

                    b.ToTable("affect_entries", t =>
                        {
                            t.HasCheckConstraint("ck_affect_arousal_range", "arousal_score  BETWEEN -5 AND 5");

                            t.HasCheckConstraint("ck_affect_dominance_range", "dominance_score BETWEEN -5 AND 5");

                            t.HasCheckConstraint("ck_affect_pleasure_range", "pleasure_score BETWEEN -5 AND 5");
                        });
                });

            modelBuilder.Entity("HabitTracker.Domain.Entities.AnalystProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnalystId")
                        .HasColumnType("uuid")
                        .HasColumnName("analyst_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("HabitId")
                        .HasColumnType("integer")
                        .HasColumnName("habit_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_analyst_proposals");

                    b.HasIndex("AnalystId")
                        .HasDatabaseName("ix_analyst_proposals_analyst_id");

                    b.HasIndex("HabitId")
                        .HasDatabaseName("ix_analyst_proposals_habit_id");

                    b.ToTable("analyst_proposals");
                });

            modelBuilder.Entity("HabitTracker.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color_hex");

                    b.Property<string>("IconEmoji")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("icon_emoji");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<bool>("IsNegative")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_negative");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("HabitTracker.Domain.Entities.Habit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<string>("ColorHex")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color_hex");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("IconEmoji")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("icon_emoji");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<bool>("IsNegative")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_negative");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_habits");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_habits_category_id");

                    b.ToTable("habits");
                });

            modelBuilder.Entity("HabitTracker.Domain.Entities.HabitExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("ExecutionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("execution_time");

                    b.Property<decimal?>("LoggedValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("logged_value");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<Guid>("UserHabitId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_habit_id");

                    b.HasKey("Id")
                        .HasName("pk_habit_executions");

                    b.HasIndex("UserHabitId", "ExecutionTime")
                        .HasDatabaseName("idx_executions_userhabit_time");

                    b.ToTable("habit_executions");
                });

            modelBuilder.Entity("HabitTracker.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_name");

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "User"
                        },
                        new
                        {
                            Id = 2,
                            Name = "ContentManager"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Analyst"
                        });
                });

            modelBuilder.Entity("HabitTracker.Domain.Entities.SleepLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("SleepEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sleep_end");

                    b.Property<int>("SleepQuality")
                        .HasColumnType("integer")
                        .HasColumnName("sleep_quality");

                    b.Property<DateTime>("SleepStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sleep_start");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("tags")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_sleep_logs");

                    b.HasIndex("UserId", "SleepStart")
                        .HasDatabaseName("idx_sleep_logs_user_time");

                    b.ToTable("sleep_logs", t =>
                        {
                            t.HasCheckConstraint("ck_sleep_end_after_start", "sleep_end > sleep_start");

                            t.HasCheckConstraint("ck_sleep_quality_range", "sleep_quality BETWEEN 1 AND 10");
                        });
                });

            modelBuilder.Entity("HabitTracker.Domain.Entities.SleepRecommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_sleep_recommendations");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_sleep_recommendations_user_id");

                    b.ToTable("sleep_recommendations");
                });

            modelBuilder.Entity("HabitTracker.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nickname");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("UTC")
                        .HasColumnName("timezone");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_users_role_id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("HabitTracker.Domain.Entities.UserAchievement", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("AchievementId")
                        .HasColumnType("integer")
                        .HasColumnName("achievement_id");

                    b.Property<int>("CurrentProgress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("current_progress");

                    b.Property<bool>("IsUnlocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_unlocked");

                    b.Property<DateTime?>("UnlockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unlocked_at");

                    b.HasKey("UserId", "AchievementId")
                        .HasName("pk_user_achievements");

                    b.HasIndex("AchievementId")
                        .HasDatabaseName("ix_user_achievements_achievement_id");

                    b.ToTable("user_achievements");
                });

            modelBuilder.Entity("HabitTracker.Domain.Entities.UserHabit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<string>("ColorHex")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color_hex");

                    b.Property<int>("CurrentStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("current_streak");

                    b.Property<string>("CustomName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("custom_name");

                    b.Property<int>("FrequencyType")
                        .HasColumnType("integer")
                        .HasColumnName("frequency_type");

                    b.Property<int?>("HabitId")
                        .HasColumnType("integer")
                        .HasColumnName("habit_id");

                    b.Property<string>("IconEmoji")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("icon_emoji");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<bool>("IsNegative")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_negative");

                    b.Property<int>("LongestStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("longest_streak");

                    b.Property<string>("MetricUnit")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("metric_unit");

                    b.Property<decimal?>("TargetValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("target_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_habits");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_user_habits_category_id");

                    b.HasIndex("HabitId")
                        .HasDatabaseName("ix_user_habits_habit_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_user_habits_user_archived")
                        .HasFilter("is_archived = false");

                    b.ToTable("user_habits");
                });

            modelBuilder.Entity("HabitTracker.Domain.Entities.UserSleepProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AbsoluteMinSleepHours")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("absolute_min_sleep_hours");

                    b.Property<decimal>("BaseSleepHours")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("base_sleep_hours");

                    b.Property<TimeOnly?>("CurrentWakeTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("current_wake_time");

                    b.Property<int>("ShiftStepMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("shift_step_minutes");

                    b.Property<int>("SleepDebtMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sleep_debt_minutes");

                    b.Property<TimeOnly>("TargetWakeTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("target_wake_time");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<decimal>("WeekendDeviationHours")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("weekend_deviation_hours");

                    b.HasKey("Id")
                        .HasName("pk_user_sleep_profiles");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_sleep_profiles_user_id");

                    b.ToTable("user_sleep_profiles", t =>
                        {
                            t.HasCheckConstraint("ck_sleep_profile_min_positive", "absolute_min_sleep_hours > 0");
                        });
                });

            modelBuilder.Entity("HabitTracker.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("idx_outbox_unprocessed_created_at")
                        .HasFilter("processed_at_utc IS NULL");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("HabitTracker.Domain.Entities.Achievement", b =>
                {
                    b.HasOne("HabitTracker.Domain.Entities.Habit", "Habit")
                        .WithMany("Achievements")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_achievements_habits_habit_id");

                    b.Navigation("Habit");
                });

            modelBuilder.Entity("HabitTracker.Domain.Entities.AffectEntry", b =>
                {
                    b.HasOne("HabitTracker.Domain.Entities.User", "User")
                        .WithMany("AffectEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_affect_entries_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HabitTracker.Domain.Entities.AnalystProposal", b =>
                {
                    b.HasOne("HabitTracker.Domain.Entities.User", "Analyst")
                        .WithMany("AnalystProposals")
                        .HasForeignKey("AnalystId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_analyst_proposals_users_analyst_id");

                    b.HasOne("HabitTracker.Domain.Entities.Habit", "Habit")
                        .WithMany("Proposals")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_analyst_proposals_habits_habit_id");

                    b.Navigation("Analyst");

                    b.Navigation("Habit");
                });

            modelBuilder.Entity("HabitTracker.Domain.Entities.Habit", b =>
                {
                    b.HasOne("HabitTracker.Domain.Entities.Category", "Category")
                        .WithMany("Habits")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_habits_categories_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("HabitTracker.Domain.Entities.HabitExecution", b =>
                {
                    b.HasOne("HabitTracker.Domain.Entities.UserHabit", "UserHabit")
                        .WithMany("Executions")
                        .HasForeignKey("UserHabitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_habit_executions_user_habits_user_habit_id");

                    b.Navigation("UserHabit");
                });

            modelBuilder.Entity("HabitTracker.Domain.Entities.SleepLog", b =>
                {
                    b.HasOne("HabitTracker.Domain.Entities.User", "User")
                        .WithMany("SleepLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sleep_logs_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HabitTracker.Domain.Entities.SleepRecommendation", b =>
                {
                    b.HasOne("HabitTracker.Domain.Entities.User", "User")
                        .WithMany("SleepRecommendations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sleep_recommendations_users_user_id");

                    b.OwnsOne("HabitTracker.Domain.ValueObjects.SleepPlan", "SleepPlan", b1 =>
                        {
                            b1.Property<Guid>("SleepRecommendationId")
                                .HasColumnType("uuid");

                            b1.HasKey("SleepRecommendationId");

                            b1.ToTable("sleep_recommendations");

                            b1.ToJson("sleep_plan");

                            b1.WithOwner()
                                .HasForeignKey("SleepRecommendationId");

                            b1.OwnsMany("HabitTracker.Domain.ValueObjects.SleepPlanDay", "Days", b2 =>
                                {
                                    b2.Property<Guid>("SleepPlanSleepRecommendationId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<DateOnly>("Date")
                                        .HasColumnType("date");

                                    b2.Property<TimeOnly>("IdealBedtime")
                                        .HasColumnType("time without time zone");

                                    b2.Property<decimal>("PlannedSleepHours")
                                        .HasColumnType("numeric");

                                    b2.Property<TimeOnly>("PlannedWake")
                                        .HasColumnType("time without time zone");

                                    b2.HasKey("SleepPlanSleepRecommendationId", "__synthesizedOrdinal");

                                    b2.ToTable("sleep_recommendations");

                                    b2.WithOwner()
                                        .HasForeignKey("SleepPlanSleepRecommendationId");

                                    b2.OwnsOne("HabitTracker.Domain.ValueObjects.Zeitgebers", "Zeitgebers", b3 =>
                                        {
                                            b3.Property<Guid>("SleepPlanDaySleepPlanSleepRecommendationId")
                                                .HasColumnType("uuid");

                                            b3.Property<int>("SleepPlanDay__synthesizedOrdinal")
                                                .HasColumnType("integer");

                                            b3.Property<TimeOnly?>("LastCaffeine")
                                                .HasColumnType("time without time zone");

                                            b3.Property<TimeOnly?>("LastMeal")
                                                .HasColumnType("time without time zone");

                                            b3.Property<TimeOnly?>("ScreensOff")
                                                .HasColumnType("time without time zone");

                                            b3.HasKey("SleepPlanDaySleepPlanSleepRecommendationId", "SleepPlanDay__synthesizedOrdinal");

                                            b3.ToTable("sleep_recommendations");

                                            b3.WithOwner()
                                                .HasForeignKey("SleepPlanDaySleepPlanSleepRecommendationId", "SleepPlanDay__synthesizedOrdinal");
                                        });

                                    b2.Navigation("Zeitgebers")
                                        .IsRequired();
                                });

                            b1.Navigation("Days");
                        });

                    b.Navigation("SleepPlan")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HabitTracker.Domain.Entities.User", b =>
                {
                    b.HasOne("HabitTracker.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_roles_role_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HabitTracker.Domain.Entities.UserAchievement", b =>
                {
                    b.HasOne("HabitTracker.Domain.Entities.Achievement", "Achievement")
                        .WithMany("UserAchievements")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_achievements_achievements_achievement_id");

                    b.HasOne("HabitTracker.Domain.Entities.User", "User")
                        .WithMany("UserAchievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_achievements_users_user_id");

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HabitTracker.Domain.Entities.UserHabit", b =>
                {
                    b.HasOne("HabitTracker.Domain.Entities.Category", "Category")
                        .WithMany("UserHabits")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_habits_categories_category_id");

                    b.HasOne("HabitTracker.Domain.Entities.Habit", "Habit")
                        .WithMany("UserHabits")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_user_habits_habits_habit_id");

                    b.HasOne("HabitTracker.Domain.Entities.User", "User")
                        .WithMany("UserHabits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_habits_users_user_id");

                    b.OwnsOne("HabitTracker.Domain.ValueObjects.ScheduleRule", "ScheduleRule", b1 =>
                        {
                            b1.Property<Guid>("UserHabitId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("DayOfMonth")
                                .HasColumnType("integer");

                            b1.PrimitiveCollection<int[]>("DaysOfWeek")
                                .HasColumnType("integer[]");

                            b1.Property<TimeOnly?>("ExactTime")
                                .HasColumnType("time without time zone");

                            b1.Property<DateOnly?>("OneTimeDate")
                                .HasColumnType("date");

                            b1.Property<int?>("TimeSlot")
                                .HasColumnType("integer");

                            b1.Property<int?>("TimesPerPeriod")
                                .HasColumnType("integer");

                            b1.HasKey("UserHabitId");

                            b1.ToTable("user_habits");

                            b1.ToJson("schedule_rule");

                            b1.WithOwner()
                                .HasForeignKey("UserHabitId");
                        });

                    b.Navigation("Category");

                    b.Navigation("Habit");

                    b.Navigation("ScheduleRule");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HabitTracker.Domain.Entities.UserSleepProfile", b =>
                {
                    b.HasOne("HabitTracker.Domain.Entities.User", "User")
                        .WithOne("SleepProfile")
                        .HasForeignKey("HabitTracker.Domain.Entities.UserSleepProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_sleep_profiles_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HabitTracker.Domain.Entities.Achievement", b =>
                {
                    b.Navigation("UserAchievements");
                });

            modelBuilder.Entity("HabitTracker.Domain.Entities.Category", b =>
                {
                    b.Navigation("Habits");

                    b.Navigation("UserHabits");
                });

            modelBuilder.Entity("HabitTracker.Domain.Entities.Habit", b =>
                {
                    b.Navigation("Achievements");

                    b.Navigation("Proposals");

                    b.Navigation("UserHabits");
                });

            modelBuilder.Entity("HabitTracker.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("HabitTracker.Domain.Entities.User", b =>
                {
                    b.Navigation("AffectEntries");

                    b.Navigation("AnalystProposals");

                    b.Navigation("SleepLogs");

                    b.Navigation("SleepProfile");

                    b.Navigation("SleepRecommendations");

                    b.Navigation("UserAchievements");

                    b.Navigation("UserHabits");
                });

            modelBuilder.Entity("HabitTracker.Domain.Entities.UserHabit", b =>
                {
                    b.Navigation("Executions");
                });
#pragma warning restore 612, 618
        }
    }
}
